<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Payment_SchedulesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('payment_schedules')->insert([

            [ 'department_id'=>1,
              'cohort'=>1,
              'year'=>'2024',
              'amount'=>120000.00,
              'purpose' => 'sch_fee',
              'description' => 'School fees payment for graphic design',
            ],
            [ 'cohort'=>1,
              'year'=>'2024',
              'amount'=>250000.00,
              'department_id'=>2,
              'purpose' => 'sch_fee',
              'description' => 'School fees payment for mobile app development',
            ],
            [ 'cohort'=>1,
            'department_id'=>3,
              'year'=>'2024',
              'amount'=>120000.00,
              'purpose' => 'sch_fee',
              'description' => 'School fees payment for UI/UX',
            ],
            [ 'cohort'=>1,
            'department_id'=>4,
              'year'=>'2024',
              'amount'=>200000.00,
              'purpose' => 'sch_fee',
              'description' => 'School fees payment for 3D modelling',
            ],
            [ 'cohort'=>1,
            'department_id'=>5,
              'year'=>'2024',
              'amount'=>250000.00,
              'purpose' => 'sch_fee',
              'description' =>  'School fees payment for 3D Animation',
            ],
            [ 'cohort'=>1,
            'department_id'=>6,
              'year'=>'2024',
              'amount'=>120000.00,
              'purpose' => 'sch_fee',
               'description' => 'School fees payment for Digital marketing',
            ],
            [ 'cohort'=>1,
            'department_id'=>7,
              'year'=>'2024',
              'amount'=>150000.00,
              'purpose' => 'sch_fee',
               'description' => 'School fees payment for Website development',
              

            ],
            [ 'cohort'=>1,
            'department_id'=>8,
            'year'=>'2024',
            'amount'=>150000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for Cyber security',
            ],
            [ 'cohort'=>1,
            'department_id'=>9,
            'year'=>'2024',
            'amount'=>150000.00,
            'purpose' => 'sch_fee',
             'description' => 'School fees payment for motion graphics',
            ],
            [ 'cohort'=>1,
            'department_id'=>10,
            'year'=>'2024',
            'amount'=>250000.00,
            'purpose' => 'sch_fee',
             'description' => 'School fees payment for Blockchain technology',
            ],
            [ 'cohort'=>1,
            'department_id'=>11,
            'year'=>'2024',
            'amount'=>50000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for sage',
            ],

            [ 'cohort'=>1,
            'department_id'=>12,
            'year'=>'2024',
            'amount'=>100000.00,
            'purpose' => 'sch_fee',
             'description' => 'School fees payment for Networking',
            ],

            [ 'cohort'=>1,
            'department_id'=>13,
            'year'=>'2024',
            'amount'=>600000.00,
            'purpose' => 'sch_fee',
             'description' => 'School fees payment for Artificial intelligence',
            ],

            [ 'cohort'=>1,
            'department_id'=>14,
            'year'=>'2024',
            'amount'=>150000.00,
            'purpose' => 'sch_fee',
             'description' => 'School fees payment for Forex Trading',
            ],
           

            [ 'cohort'=>1,
            'department_id'=>15,
            'year'=>'2024',
            'amount'=>200000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for Advanced Backend programming',
            ],

            [ 'cohort'=>1,
            'department_id'=>16,
            'year'=>'2024',
            'amount'=>150000.00,
            'purpose' => ' Sch Fee',
            'description' =>  'School fees payment for Advanced frontend programming',
            ],

            [ 'cohort'=>1,
            'department_id'=>17,
            'year'=>'2024',
            'amount'=>200000.00,
            'purpose' => 'sch_fee',
             'description' => 'School fees payment for cloud computing',
            ],

            [ 'cohort'=>1,
            'department_id'=>18,
            'year'=>'2024',
            'amount'=>150000.00,
            'purpose' => ' Sch Fee',
            'description' =>  'School fees payment for Data science/analysis',
            ],

            [ 'cohort'=>1,
            'department_id'=>19,
            'year'=>'2024',
            'amount'=>50000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for master microsoft excel',
            ],

            [ 'cohort'=>1,
            'department_id'=>20,
            'year'=>'2024',
            'amount'=>80000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for for copywriting',
            ],

            [ 'cohort'=>1,
            'department_id'=>21,
            'year'=>'2024',
            'amount'=>550000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for Software engineering',
            ],

            [ 'cohort'=>1,
            'department_id'=>22,
            'year'=>'2024',
            'amount'=>100000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for R programming',
            ],

            [ 'cohort'=>1,
            'department_id'=>23,
            'year'=>'2024',
            'amount'=>80000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for Data_visualization',
            ],

            [ 'cohort'=>1,
            'department_id'=>24,
            'year'=>'2024',
            'amount'=>60000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for word press web design',
            ],

            [ 'cohort'=>1,
            'department_id'=>25,
            'year'=>'2024',
            'amount'=>80000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for Adobe illustrator',
            ],

            [ 'cohort'=>1,
            'department_id'=>26,
            'year'=>'2024',
            'amount'=>150000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for for autocad',
            

            ],

            [ 'cohort'=>1,
            'department_id'=>27,
            'year'=>'2024',
            'amount'=>250000.00,
            'purpose' => 'sch_fee',
             'description' => 'School fees payment for interior design',
            ],

            [ 'cohort'=>1,
            'department_id'=>28,
            'year'=>'2024',
            'amount'=>200000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for It auditing',
            ],

            [ 'cohort'=>1,
            'department_id'=>29,
            'year'=>'2024',
            'amount'=>150000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for master python',
            ],

            [ 'cohort'=>1,
            'department_id'=>30,
            'year'=>'2024',
            'amount'=>150000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for master javascript',
            ],

            [ 'cohort'=>1,
            'department_id'=>31,
            'year'=>'2024',
            'amount'=>50000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for data processing',
            ],

            [ 'cohort'=>1,
            'department_id'=>32,
            'year'=>'2024',
            'amount'=>150000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for master react',
            ],

            [ 'cohort'=>1,
            'department_id'=>33,
            'year'=>'2024',
            'amount'=>150000.00,
            'purpose' => 'sch_fee',
            'description' =>   'School fees payment for master jquery',
            ],

            [ 'cohort'=>1,
              'department_id'=>34,
            'year'=>'2024',
            'amount'=>150000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for master ajax',
            ],

            [ 'cohort'=>1,
            'department_id'=>35,
            'year'=>'2024',
            'amount'=>250000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for for master php',
            ],

            [ 'cohort'=>1,
            'department_id'=>36,
            'year'=>'2024',
            'amount'=>250000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for master C++',
            ],

            [ 'cohort'=>1,
            'department_id'=>37,
            'year'=>'2024',
            'amount'=>150000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for master C#',
            ],

            [ 'cohort'=>1,
            'department_id'=>38,
            'year'=>'2024',
            'amount'=>200000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for master node js',
            ],

            [ 'cohort'=>1,
            'department_id'=>39,
            'year'=>'2024',
            'amount'=>120000.00,
            'purpose' => 'sch_fee',
            'description' =>   'School fees payment for master bootstrap',
            ],

            [ 'cohort'=>1,
            'department_id'=>40,
            'year'=>'2024',
            'amount'=>150000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for master CSS',
            ],

            [ 'cohort'=>1,
            'department_id'=>41,
            'year'=>'2024',
            'amount'=>50000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for skill monetization',
            ],

            [ 'cohort'=>1,
            'department_id'=>42,
            'year'=>'2024',
            'amount'=>50000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for technical writing',
            ],

            [ 'cohort'=>1,
            'department_id'=>43,
            'year'=>'2024',
            'amount'=>250000.00,
            'purpose' => 'sch_fee',
            'description' =>   'School fees payment for video editing',
            ],

            [ 'cohort'=>1,
            'department_id'=>44,
            'year'=>'2024',
            'amount'=>200000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for linux',
            ],
            [ 'cohort'=>1,
            'department_id'=>45,
            'year'=>'2024',
            'amount'=>50000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for for canva',
            ],
            [ 'cohort'=>1,
            'department_id'=>46,
            'year'=>'2024',
            'amount'=>150000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for cryptocurrency',
            ],
            [ 'cohort'=>1,
            'department_id'=>47,
            'year'=>'2024',
            'amount'=>150000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for agile methodology',
            ],
            [ 'cohort'=>1,
            'department_id'=>48,
            'year'=>'2024',
            'amount'=>150000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for scrum',
            ],
            [ 'cohort'=>1,
            'department_id'=>49,
            'year'=>'2024',
            'amount'=>250000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for kanban',
            ],
            [ 'cohort'=>1,
            'department_id'=>50,
            'year'=>'2024',
            'amount'=>150000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for gira',
            ],
            [ 'cohort'=>1,
            'department_id'=>51,
            'year'=>'2024',
            'amount'=>100000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for microsoft project',
            ],
            [ 'cohort'=>1,
            'department_id'=>52,
            'year'=>'2024',
            'amount'=>100000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for trello',
            ],
            [ 'cohort'=>1,
            'department_id'=>53,
            'year'=>'2024',
            'amount'=>100000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for asana',
            ],
            [ 'cohort'=>1,
            'department_id'=>54,
            'year'=>'2024',
            'amount'=>120000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for version control',
            ],
            [ 'cohort'=>1,
            'department_id'=>55,
            'year'=>'2024',
            'amount'=>100000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for communication tools ',
            ],
            [ 'cohort'=>1,
            'department_id'=>56,
            'year'=>'2024',
            'amount'=>100000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for time management',
            ],
            [ 'cohort'=>1,
            'department_id'=>57,
            'year'=>'2024',
            'amount'=>150000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for linux administration',
            ],
            [ 'cohort'=>1,
            'department_id'=>58,
            'year'=>'2024',
            'amount'=>150000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for window server administration',
            ],
            [ 'cohort'=>1,
            'department_id'=>59,
            'year'=>'2024',
            'amount'=>130000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for MacOS proficiency ',
            ],
            [ 'cohort'=>1,
            'department_id'=>60,
            'year'=>'2024',
            'amount'=>120000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for shell scripting',
            ],
            [ 'cohort'=>1,
            'department_id'=>61,
            'year'=>'2024',
            'amount'=>130000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for virtualization',
            ],
            [ 'cohort'=>1,
            'department_id'=>62,
            'year'=>'2024',
            'amount'=>130000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for containerization',
            ],
            [ 'cohort'=>1,
            'department_id'=>63,
            'year'=>'2024',
            'amount'=>150000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for  system monitoring',
            ],
            [ 'cohort'=>1,
            'department_id'=>64,
            'year'=>'2024',
            'amount'=>100000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for patch management',
            ],
            [ 'cohort'=>1,
            'department_id'=>65,
            'year'=>'2024',
            'amount'=>80000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for active directory',
            ],
            [ 'cohort'=>1,
            'department_id'=>66,
            'year'=>'2024',
            'amount'=>100000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for file system management',
            ],
            [ 'cohort'=>1,
            'department_id'=>67,
            'year'=>'2024',
            'amount'=>120000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for hardware diagonistics',
            ],
            [ 'cohort'=>1,
            'department_id'=>68,
            'year'=>'2024',
            'amount'=>60000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for software installation',
            ],
            [ 'cohort'=>1,
            'department_id'=>69,
            'year'=>'2024',
            'amount'=>150000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for remote desktop support',
            ],
            [ 'cohort'=>1,
            'department_id'=>70,
            'year'=>'2024',
            'amount'=>150000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for end-user training',
            ],
            [ 'cohort'=>1,
            'department_id'=>71,
            'year'=>'2024',
            'amount'=>130000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for troubleshooting networks',
            ],
            [ 'cohort'=>1,
            'department_id'=>72,
            'year'=>'2024',
            'amount'=>120000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for system optimization',
            ],
            [ 'cohort'=>1,
            'department_id'=>73,
            'year'=>'2024',
            'amount'=>120000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for data recovery',
            ],
            [ 'cohort'=>1,
            'department_id'=>74,
            'year'=>'2024',
            'amount'=>50000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for malware removal',
            ],
            [ 'cohort'=>1,
            'department_id'=>75,
            'year'=>'2024',
            'amount'=>150000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for peripheral setup',
            ],
            [ 'cohort'=>1,
            'department_id'=>76,
            'year'=>'2024',
            'amount'=>150000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for disaster removal',
            ],
            [ 'cohort'=>1,
            'department_id'=>77,
            'year'=>'2024',
            'amount'=>250000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for geographic information',
            ],
            [ 'cohort'=>1,
            'department_id'=>78,
            'year'=>'2024',
            'amount'=>100000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for web mapping',
            ],
            [ 'cohort'=>1,
            'department_id'=>79,
            'year'=>'2024',
            'amount'=>130000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for remote sensing',
            ],
            [ 'cohort'=>1,
            'department_id'=>80,
            'year'=>'2024',
            'amount'=>250000.00,
            'purpose' => 'sch_fee',
            'description' =>  'School fees payment for quantum computing',
            ],











        ]);
    }
}
